Updated from boilerplate
MapColonies/osm-change-generator-server pull request #75
Opened 2023-07-27 07:44 UTC by NatalieShaked

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-09-04 08:46 UTC, melancholiai requested changes

2023-09-04 08:46 UTC, melancholiai commented on src/change/controllers/changeController.ts
>    public createResource: CreateResourceHandler = (req, res, next) => {
use non generic function name

2023-09-04 08:46 UTC, melancholiai commented on src/change/controllers/changeController.ts
> +    this.createdChangeCounter = meter.createCounter('created_change');
metrics should be calculated inside the `ChangeManager` where we handle business logic
also, `generated_changes` is clearer due to osm `create` meaning

2023-11-12 21:09 UTC, shimoncohen commented
Please change PR to commitlint standards.

2025-02-13 11:48 UTC, closed without merging